---
- name: Upgrade all packages
  dnf:
    name: '*'
    state: latest
  when: update_all

# - include_tasks: rpmfusion.yml

- include_tasks: vscode.yml
  when: "'code' in packages_to_install"

- include_tasks: gh.yml
  when: "'gh' in packages_to_install"

- name: Enable proxy for some repos
  command: dnf config-manager --save --setopt=*.proxy={{ socks5h_proxy }} {{ repos_need_proxy | join(' ') }}
  when: repos_need_proxy | length > 0
  args:
    warn: no

# https://github.com/ansible/ansible/issues/64852#issuecomment-720124832
- name: 'Enable modules'
  command: dnf module enable -y "{{ item }}"
  register: result
  changed_when:
    - '"Enabling module streams" in result.stdout'
  loop: '{{ modules_to_enable }}'

- name: Install packages
  dnf:
    name: '{{ packages_to_install }}'
# https://github.com/nodesource/distributions/#installation-instructions-1
