---
# https://fedoraproject.org/wiki/Workstation/Third_Party_Software_Repositories#Managing_third_party_repositories_using_DNF
- name: Install some third party repos
  dnf:
    name: fedora-workstation-repositories
    state: present
# TODO: state changed

- name: Enable some repos above
  command:
    cmd: dnf config-manager --set-enabled google-chrome phracek-PyCharm
    warn: no

# https://rpmfusion.org/Configuration
- name: Install RPM Fusion repos
  dnf:
    name: '{{ RPM_fusion_repos }}'
    disable_gpg_check: yes
    state: present
