---
# Rime configs ware restored in the `dotfiles` role
# This task will update part of Rime and restart ibus
# https://github.com/rime/plum
- name: Download Plum and install double-pinyin, emoji
  vars:
    plum_repo: '{{ ansible_user_dir }}/.local/share/plum'
  block:
    - name: Clone the plum repo
      git:
        repo: https://github.com/rime/plum.git
        depth: 1
        dest: '{{ plum_repo }}'

# https://github.com/rime/plum#advanced-usage
# https://github.com/rime/rime-emoji
# https://github.com/rime/rime-emoji/issues/7#issuecomment-557855369
    - name: Install preset, double pinyin, Emoji
      shell:
        chdir: '{{ plum_repo }}'
        cmd: 'bash rime-install :preset double-pinyin emoji emoji:customize:schema=double_pinyin_mspy'

# the psutil module need to be installed. `sudo dnf install python3-psutil`
- name: Add Rime to input sources
  community.general.dconf:
    key: '/org/gnome/desktop/input-sources/sources'
    value: "[('xkb', 'us'), ('ibus', 'rime')]"
    state: present

- name: Restart ibus
  command: ibus restart
  args:
    warn: no
